"""create sessions steps task_memory tables

Revision ID: ea55aae614c9
Revises: 
Create Date: 2026-04-11 14:49:04.769638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea55aae614c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('task', sa.String(length=256), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETE', 'FAILED', 'EXPIRED', name='sessionstatus'), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('task_memory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=256), nullable=False),
    sa.Column('learned_flow', sa.JSON(), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_memory_task_type'), 'task_memory', ['task_type'], unique=False)
    op.create_index(op.f('ix_task_memory_user_id'), 'task_memory', ['user_id'], unique=False)
    op.create_table('steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_token', sa.String(length=32), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('NAVIGATE', 'HIGHLIGHT', 'FILL', 'CLICK', 'WAIT', name='stepaction'), nullable=False),
    sa.Column('selector', sa.String(length=512), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('prefill_value', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('is_skippable', sa.Boolean(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_token'], ['sessions.token'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steps_session_token'), 'steps', ['session_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steps_session_token'), table_name='steps')
    op.drop_table('steps')
    op.drop_index(op.f('ix_task_memory_user_id'), table_name='task_memory')
    op.drop_index(op.f('ix_task_memory_task_type'), table_name='task_memory')
    op.drop_table('task_memory')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
